	@Test
	public void testTagKind() {
		try (Git git = new Git(db)) {
			assertTrue(git.tag().isAnnotated());
			assertTrue(git.tag().setSigned(true).isAnnotated());
			assertTrue(git.tag().setSigned(false).isAnnotated());
			assertTrue(git.tag().setSigningKey(null).isAnnotated());
			assertTrue(git.tag().setSigningKey("something").isAnnotated());
			assertTrue(git.tag().setSigned(false).setSigningKey(null)
					.isAnnotated());
			assertTrue(git.tag().setSigned(false).setSigningKey("something")
					.isAnnotated());
			assertTrue(git.tag().setSigned(true).setSigningKey(null)
					.isAnnotated());
			assertTrue(git.tag().setSigned(true).setSigningKey("something")
					.isAnnotated());
			assertTrue(git.tag().setAnnotated(true).isAnnotated());
			assertTrue(
					git.tag().setAnnotated(true).setSigned(true).isAnnotated());
			assertTrue(git.tag().setAnnotated(true).setSigned(false)
					.isAnnotated());
			assertTrue(git.tag().setAnnotated(true).setSigningKey(null)
					.isAnnotated());
			assertTrue(git.tag().setAnnotated(true).setSigningKey("something")
					.isAnnotated());
			assertTrue(git.tag().setAnnotated(true).setSigned(false)
					.setSigningKey(null).isAnnotated());
			assertTrue(git.tag().setAnnotated(true).setSigned(false)
					.setSigningKey("something").isAnnotated());
			assertTrue(git.tag().setAnnotated(true).setSigned(true)
					.setSigningKey(null).isAnnotated());
			assertTrue(git.tag().setAnnotated(true).setSigned(true)
					.setSigningKey("something").isAnnotated());
			assertFalse(git.tag().setAnnotated(false).isAnnotated());
			assertTrue(git.tag().setAnnotated(false).setSigned(true)
					.isAnnotated());
			assertFalse(git.tag().setAnnotated(false).setSigned(false)
					.isAnnotated());
			assertFalse(git.tag().setAnnotated(false).setSigningKey(null)
					.isAnnotated());
			assertTrue(git.tag().setAnnotated(false).setSigningKey("something")
					.isAnnotated());
			assertFalse(git.tag().setAnnotated(false).setSigned(false)
					.setSigningKey(null).isAnnotated());
			assertTrue(git.tag().setAnnotated(false).setSigned(false)
					.setSigningKey("something").isAnnotated());
			assertTrue(git.tag().setAnnotated(false).setSigned(true)
					.setSigningKey(null).isAnnotated());
			assertTrue(git.tag().setAnnotated(false).setSigned(true)
					.setSigningKey("something").isAnnotated());
		}
	}

